name: Docker Image Build Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-docker-image .

    - name: Start Docker container
      run: docker run -d -p 8000:8000 -p 5000:5000 --network host --name my-container my-docker-image -j inference

    - name: Ping inference endpoint
      run: curl -s -o /dev/null -w "%{http_code}" http://0.0.0.0:8000/infer

    - name: Cleanup Docker container
      run: docker stop my-container && docker rm my-container
